// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqHDtVT7Ar3bXM4WIVKRU2IOVPJZotLv4',
    appId: '1:747694275611:web:4f35aef628539553f24cbe',
    messagingSenderId: '747694275611',
    projectId: 'seaaegis',
    authDomain: 'seaaegis.firebaseapp.com',
    storageBucket: 'seaaegis.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGoljXNJahEy0Nn763CNvox0qx-gEq4QM',
    appId: '1:747694275611:android:acb7d7e53ac75f97f24cbe',
    messagingSenderId: '747694275611',
    projectId: 'seaaegis',
    storageBucket: 'seaaegis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6x8n-03S-V6BkqUDWcTzC9BmZRrCapIE',
    appId: '1:747694275611:ios:dc78897456b79945f24cbe',
    messagingSenderId: '747694275611',
    projectId: 'seaaegis',
    storageBucket: 'seaaegis.appspot.com',
    iosBundleId: 'com.example.seaaegis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6x8n-03S-V6BkqUDWcTzC9BmZRrCapIE',
    appId: '1:747694275611:ios:dc78897456b79945f24cbe',
    messagingSenderId: '747694275611',
    projectId: 'seaaegis',
    storageBucket: 'seaaegis.appspot.com',
    iosBundleId: 'com.example.seaaegis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqHDtVT7Ar3bXM4WIVKRU2IOVPJZotLv4',
    appId: '1:747694275611:web:22235285387feee2f24cbe',
    messagingSenderId: '747694275611',
    projectId: 'seaaegis',
    authDomain: 'seaaegis.firebaseapp.com',
    storageBucket: 'seaaegis.appspot.com',
  );
}
